SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_MAX_SPEED = 300
PLAYER_ACCEL = 200
PLAYER_DECEL = 300

PLAYER_SHOOT_COOLDOWN = 0.3  # seconds
PLAYER_SHOOT_SPEED = 500
PLAYER_MISSILE_COOLDOWN = 2
PLAYER_MISSILE_SHOOT_SPEED = 1000

SHOT_RADIUS = 5
MISSILE_RADIUS = 2