SCREEN_WIDTH = 1920
SCREEN_HEIGHT = 1080

ASTEROID_MIN_RADIUS = 20
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS
PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200
SHOT_RADIUS = 5
PLAYER_SHOT_SPEED = 400
PLAYER_SHOT_COOLDOWN = 0.45
MISSLE_SPEED = 600
MISSLE_COOLDOWN = 2
MISSLE_BORDER = 2
POWERUP_RADIUS = 20
POWERUP_SPAWN_RATE = 5
